<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Models\Concerns\TenantScoped;
use App\Models\Scopes\TenantScope;
use App\Traits\Auditable;

class Product extends Model
{
    use HasFactory, SoftDeletes, TenantScoped, Auditable;

    protected static function booted(): void
    {
        static::addGlobalScope(new TenantScope());
    }

    // SKU is generated by the backend and must be immutable by clients.
    // Do not include `sku` in fillable to avoid mass-assignment from requests.
    protected $fillable = [
        'tenant_id', 'category_id', 'barcode', 'name', 'description', 'image_url', 'price', 'cost', 'stock_min', 'custom_fields', 'is_active'
    ];

    protected $casts = [
        'custom_fields' => 'array',
        'price' => 'decimal:2',
        'cost' => 'decimal:2',
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function stock()
    {
        return $this->hasMany(Stock::class);
    }

    /**
     * Generate a short SKU string for a tenant. Ensures (best-effort) uniqueness within tenant.
     * Throws exception if unable to generate a unique SKU after retries.
     */
    public static function generateSku(int $tenantId, int $retries = 8): string
    {
        for ($i = 0; $i < $retries; $i++) {
            // Example SKU: T{tenantId}-{random8}
            $random = strtoupper(substr(bin2hex(random_bytes(4)), 0, 8));
            $sku = "T{$tenantId}-{$random}";

            $exists = self::withoutGlobalScopes()->where('tenant_id', $tenantId)->where('sku', $sku)->exists();
            if (! $exists) return $sku;
        }

        throw new \RuntimeException('Unable to generate unique SKU after multiple attempts');
    }
}

